### ISSUE TITLE
align_to_template.sh can't run with dHCP 3rd release (unsuitable file directory structure)

### ISSUE THREAD

**Issue by YaoMeng94** [ecr05/dHCP_template_alignment#1]
Hi Emma,
    I try to follow the instruction of this repository to register the native surface to template surface using MSM, but it seems the file used in the script try to seek files under "/dHCP_anat_pipeline/subjectID/sessionID/anat/Native", but in the 3rd release, there is no such directory under "anat" folder, and the file names of metrics also unmatched between the 3rd release data repository and the script.
    Is there something that needed for me to modify or it will be solved in the future relaese?
    looking forward your response, huge thanks!

Yao Meng
UESTC

**Comment by ecr05** [comment]
Hi Yao

Can you repost to the dHCP neurostars list so that Logan and others can help answer this. I don't know what the directory structure of the data is post BIDS, sorry

Emma

**Comment by YaoMeng94** [comment]
Thanks Emma, I forget the Neurostar stuff😂
